import os

os.environ[
    "USERCREDS"
] = "<ENCRYPTED USER CREDENTIALS FOR SPOTIFY PREMIUM ACCOUNT>"
os.environ["REFRESH_TOKEN"] = "<SPOTIFY REFRESH TOKEN>"
os.environ["DEVICE_ID"] = "<SPOTIFY DEVICE ID>"
os.environ["DATABASE_URL"] = "<DATABASE FILE OR URL>"
os.environ["MUSIC_LIBRARY"] = "<MUSIC FOLDER URL>"
os.environ["DEVELOPMENT"] = "False"
