music_directory         "/path/to/music"
db_file                 "/path/to/config/database"
log_file                "syslog"
state_file              "/path/to/config/state"
restore_paused          "yes"
auto_update             "yes"
zeroconf_enabled        "no"
input {
        plugin          "curl"
}
decoder {
        plugin          "hybrid_dsd"
        enabled         "no"
}
decoder {
        plugin          "wildmidi"
        enabled         "no"
}
audio_output {
        type            "alsa"
        name            "Headphones"
        device          "hw:CARD=Headphones,DEV=0" # optional
}
volume_normalization    "no"
filesystem_charset      "UTF-8"
