[global]
username_cmd = "jq -r .username /path/to/credentials.json"
backend = "alsa"
mixer = "PCM"
device_name = "device_name"
bitrate = 160
cache_path = "/path/to/cache/spotifyd"
max_cache_size = 1000000000
no_audio_cache = true
initial_volume = 100
volume_normalisation = true
normalisation_pregain = 3
device_type = "speaker"
